package pl.kostrowski.doka.jzwroty.model.excel;

import lombok.Data;

import java.time.LocalDate;

@Data
public class MainProductGroupExcel {
	//This class is AutoGenerated from csv definition	private JavaType FieldNameInClass;

	private String mainProductGroupCode;

	private String mainProductGroupText;

}