package pl.kostrowski.doka.jzwroty.model.excel;

import lombok.Data;

import java.time.LocalDate;

@Data
public class ProjectExcel {
	//This class is AutoGenerated from csv definition	private JavaType FieldNameInClass;

	private String projectLeadingBranch;

	private String rentalProjectNumber;

	private String rentalProjectName;

	private String jobSiteNumber;

	private String customerNumber;

	private String customerName;

	private String salesManCommissionDivision;

	private String salesManTurnoverDivision;

}