package pl.kostrowski.doka.jzwroty.model.excel;

import lombok.Data;

@Data
public class SalesmanExcel {
	//This class is AutoGenerated from csv definition	private JavaType FieldNameInClass;

	private String salesmanCode;

	private String salesmanName;

	private String branchName;

}