package pl.kostrowski.doka.jzwroty.model.excel;

import lombok.Data;

import java.time.LocalDate;

@Data
public class SalesmanExcel {
	//This class is AutoGenerated from csv definition	private JavaType FieldNameInClass;

	private String salesmanCode;

	private String SalesmanName;

}